# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${tags}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${dataset_type}${datamodule.split_id}_${tags}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${tags}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${dataset_type}${datamodule.split_id}_${tags}
  subdir: ${hydra.job.num}

